version: '2.1'

services:
  safira_api:
    image: safira_api
    container_name: safira
    build: .
    ports:
      - 8080:8080
    networks: 
      - backend
  banco:
    image: mysql:5.6
    container_name: mysql-container
    environment: 
      - MYSQL_ROOT_PASSWORD=SafiraLabApp
      - MYSQL_DATABASE=safira
      - MYSQL_USER=safiraBanco
      - MYSQL_USER_PASSWORD=SafiraLabApp
    volumes: 
      - .data:/var/lib/mysql
    ports:
      - 3306:3306
    networks: 
      - backend
networks:
  backend:
    driver: bridge